### ISSUE TITLE
update build to work with Ubuntu 22.04

### ISSUE THREAD

**Issue by lsf37** [seL4/docs#165]
As discovered in #164, the docsite build is breaking with the default versions of ruby and bundler on Ubuntu 22.04.

We should update the dependencies such that they are more stable and at least work with both 20.04 and 22.04.

**Comment by Ivan-Velickovic** [comment]
What's weird is that the Docker container on Ubuntu 22.04 doesn't seem to work for me, can't tell if it's something else or because of Ubuntu 22.04:
```
  Dependency Error: Yikes! It looks like you don't have /docs/_plugins/breadcrumbs.rb or one of its dependencies installed. In order to use Jekyll as currently configured, you'll need to install this gem. If you've run Jekyll with `bundle exec`, ensure that you have included the /docs/_plugins/breadcrumbs.rb gem in your Gemfile as well. The full error message from Ruby is: 'cannot load such file -- /docs/_plugins/breadcrumbs.rb' If you run into trouble, you can find helpful resources at https://jekyllrb.com/help/! 
                    ------------------------------------------------
      Jekyll 4.0.1   Please append `--trace` to the `build` command 
                     for any additional information or backtrace. 
                    ------------------------------------------------
Traceback (most recent call last):
	38: from /usr/local/bin/bundle:23:in `<main>'
	37: from /usr/local/bin/bundle:23:in `load'
	36: from /usr/local/lib/ruby/gems/2.7.0/gems/bundler-2.1.4/libexec/bundle:34:in `<top (required)>'
	35: from /usr/local/lib/ruby/2.7.0/bundler/friendly_errors.rb:123:in `with_friendly_errors'
	34: from /usr/local/lib/ruby/gems/2.7.0/gems/bundler-2.1.4/libexec/bundle:46:in `block in <top (required)>'
	33: from /usr/local/lib/ruby/2.7.0/bundler/cli.rb:24:in `start'
	32: from /usr/local/lib/ruby/2.7.0/bundler/vendor/thor/lib/thor/base.rb:476:in `start'
	31: from /usr/local/lib/ruby/2.7.0/bundler/cli.rb:30:in `dispatch'
	30: from /usr/local/lib/ruby/2.7.0/bundler/vendor/thor/lib/thor.rb:399:in `dispatch'
	29: from /usr/local/lib/ruby/2.7.0/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
	28: from /usr/local/lib/ruby/2.7.0/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
	27: from /usr/local/lib/ruby/2.7.0/bundler/cli.rb:476:in `exec'
	26: from /usr/local/lib/ruby/2.7.0/bundler/cli/exec.rb:28:in `run'
	25: from /usr/local/lib/ruby/2.7.0/bundler/cli/exec.rb:63:in `kernel_load'
	24: from /usr/local/lib/ruby/2.7.0/bundler/cli/exec.rb:63:in `load'
	23: from /usr/local/bundle/bin/jekyll:23:in `<top (required)>'
	22: from /usr/local/bundle/bin/jekyll:23:in `load'
	21: from /usr/local/bundle/gems/jekyll-4.0.1/exe/jekyll:15:in `<top (required)>'
	20: from /usr/local/bundle/gems/mercenary-0.3.6/lib/mercenary.rb:19:in `program'
	19: from /usr/local/bundle/gems/mercenary-0.3.6/lib/mercenary/program.rb:42:in `go'
	18: from /usr/local/bundle/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `execute'
	17: from /usr/local/bundle/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `each'
	16: from /usr/local/bundle/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `block in execute'
	15: from /usr/local/bundle/gems/jekyll-4.0.1/lib/jekyll/commands/build.rb:18:in `block (2 levels) in init_with_program'
	14: from /usr/local/bundle/gems/jekyll-4.0.1/lib/jekyll/command.rb:89:in `process_with_graceful_fail'
	13: from /usr/local/bundle/gems/jekyll-4.0.1/lib/jekyll/command.rb:89:in `each'
	12: from /usr/local/bundle/gems/jekyll-4.0.1/lib/jekyll/command.rb:89:in `block in process_with_graceful_fail'
	11: from /usr/local/bundle/gems/jekyll-4.0.1/lib/jekyll/commands/build.rb:30:in `process'
	10: from /usr/local/bundle/gems/jekyll-4.0.1/lib/jekyll/commands/build.rb:30:in `new'
	 9: from /usr/local/bundle/gems/jekyll-4.0.1/lib/jekyll/site.rb:34:in `initialize'
	 8: from /usr/local/bundle/gems/jekyll-4.0.1/lib/jekyll/site.rb:124:in `setup'
	 7: from /usr/local/bundle/gems/jekyll-4.0.1/lib/jekyll/plugin_manager.rb:21:in `conscientious_require'
	 6: from /usr/local/bundle/gems/jekyll-4.0.1/lib/jekyll/plugin_manager.rb:87:in `require_plugin_files'
	 5: from /usr/local/bundle/gems/jekyll-4.0.1/lib/jekyll/plugin_manager.rb:87:in `each'
	 4: from /usr/local/bundle/gems/jekyll-4.0.1/lib/jekyll/plugin_manager.rb:89:in `block in require_plugin_files'
	 3: from /usr/local/bundle/gems/jekyll-4.0.1/lib/jekyll/external.rb:57:in `require_with_graceful_fail'
	 2: from /usr/local/bundle/gems/jekyll-4.0.1/lib/jekyll/external.rb:57:in `each'
	 1: from /usr/local/bundle/gems/jekyll-4.0.1/lib/jekyll/external.rb:60:in `block in require_with_graceful_fail'
/usr/local/bundle/gems/jekyll-4.0.1/lib/jekyll/external.rb:60:in `require': cannot load such file -- /docs/_plugins/breadcrumbs.rb (LoadError)
	38: from /usr/local/bin/bundle:23:in `<main>'
	37: from /usr/local/bin/bundle:23:in `load'
	36: from /usr/local/lib/ruby/gems/2.7.0/gems/bundler-2.1.4/libexec/bundle:34:in `<top (required)>'
	35: from /usr/local/lib/ruby/2.7.0/bundler/friendly_errors.rb:123:in `with_friendly_errors'
	34: from /usr/local/lib/ruby/gems/2.7.0/gems/bundler-2.1.4/libexec/bundle:46:in `block in <top (required)>'
	33: from /usr/local/lib/ruby/2.7.0/bundler/cli.rb:24:in `start'
	32: from /usr/local/lib/ruby/2.7.0/bundler/vendor/thor/lib/thor/base.rb:476:in `start'
	31: from /usr/local/lib/ruby/2.7.0/bundler/cli.rb:30:in `dispatch'
	30: from /usr/local/lib/ruby/2.7.0/bundler/vendor/thor/lib/thor.rb:399:in `dispatch'
	29: from /usr/local/lib/ruby/2.7.0/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
	28: from /usr/local/lib/ruby/2.7.0/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
	27: from /usr/local/lib/ruby/2.7.0/bundler/cli.rb:476:in `exec'
	26: from /usr/local/lib/ruby/2.7.0/bundler/cli/exec.rb:28:in `run'
	25: from /usr/local/lib/ruby/2.7.0/bundler/cli/exec.rb:63:in `kernel_load'
	24: from /usr/local/lib/ruby/2.7.0/bundler/cli/exec.rb:63:in `load'
	23: from /usr/local/bundle/bin/jekyll:23:in `<top (required)>'
	22: from /usr/local/bundle/bin/jekyll:23:in `load'
	21: from /usr/local/bundle/gems/jekyll-4.0.1/exe/jekyll:15:in `<top (required)>'
	20: from /usr/local/bundle/gems/mercenary-0.3.6/lib/mercenary.rb:19:in `program'
	19: from /usr/local/bundle/gems/mercenary-0.3.6/lib/mercenary/program.rb:42:in `go'
	18: from /usr/local/bundle/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `execute'
	17: from /usr/local/bundle/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `each'
	16: from /usr/local/bundle/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `block in execute'
	15: from /usr/local/bundle/gems/jekyll-4.0.1/lib/jekyll/commands/build.rb:18:in `block (2 levels) in init_with_program'
	14: from /usr/local/bundle/gems/jekyll-4.0.1/lib/jekyll/command.rb:89:in `process_with_graceful_fail'
	13: from /usr/local/bundle/gems/jekyll-4.0.1/lib/jekyll/command.rb:89:in `each'
	12: from /usr/local/bundle/gems/jekyll-4.0.1/lib/jekyll/command.rb:89:in `block in process_with_graceful_fail'
	11: from /usr/local/bundle/gems/jekyll-4.0.1/lib/jekyll/commands/build.rb:30:in `process'
	10: from /usr/local/bundle/gems/jekyll-4.0.1/lib/jekyll/commands/build.rb:30:in `new'
	 9: from /usr/local/bundle/gems/jekyll-4.0.1/lib/jekyll/site.rb:34:in `initialize'
	 8: from /usr/local/bundle/gems/jekyll-4.0.1/lib/jekyll/site.rb:124:in `setup'
	 7: from /usr/local/bundle/gems/jekyll-4.0.1/lib/jekyll/plugin_manager.rb:21:in `conscientious_require'
	 6: from /usr/local/bundle/gems/jekyll-4.0.1/lib/jekyll/plugin_manager.rb:87:in `require_plugin_files'
	 5: from /usr/local/bundle/gems/jekyll-4.0.1/lib/jekyll/plugin_manager.rb:87:in `each'
	 4: from /usr/local/bundle/gems/jekyll-4.0.1/lib/jekyll/plugin_manager.rb:89:in `block in require_plugin_files'
	 3: from /usr/local/bundle/gems/jekyll-4.0.1/lib/jekyll/external.rb:57:in `require_with_graceful_fail'
	 2: from /usr/local/bundle/gems/jekyll-4.0.1/lib/jekyll/external.rb:57:in `each'
	 1: from /usr/local/bundle/gems/jekyll-4.0.1/lib/jekyll/external.rb:58:in `block in require_with_graceful_fail'
/usr/local/bundle/gems/jekyll-4.0.1/lib/jekyll/external.rb:73:in `rescue in block in require_with_graceful_fail': /docs/_plugins/breadcrumbs.rb (Jekyll::Errors::MissingDependencyException)
make: *** [Makefile:95: build] Error 1
make: *** [Makefile:83: docker_serve] Error 2
```
